---
title: "artigo"
author: "Caroline Fabrin"
date: "05/06/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(readr)
library(tidyverse)  
## Load sandwich package for robust estimator of glm
library(sandwich)
## Load lmtest package for coeftest of glm
library(lmtest)


```



```{r include=FALSE}

base_inter <- read_csv("bases/base_inter.csv")

```


```{r include=FALSE}

base_inter$OBITO <- ifelse(base_inter$EVOLUCAO == 2, 1,0)  #Coluna de óbito: 0 = NÃO ÕBITO, 1 = ÕBITO
base_inter$AMOSTRA <- ifelse(base_inter$AMOSTRA == 1, 1,0) #Coluna de coleta de amostra: 0 = NÃO COLETOU; 1 = COLETOU
base_inter$DT_RAIOX <- ifelse(is.na(base_inter$DT_RAIOX), 0,1) #Coluna Rx: 0 = NÃO FEZ; 1 = FEZ
base_inter$DT_TOMO <- ifelse(is.na(base_inter$DT_TOMO), 0,1) #Coluna Tomo: 0 = NÃO FEZ; 1 = FEZ
base_inter$UTI <- ifelse(base_inter$UTI == 1, 1,0) #Coluna de UTI: 0 = NÃO UTI; 1 = UTI

base_inter$`Decil de IDH-M` <- as.factor(base_inter$`Decil de IDH-M`)


#Dividindo UTI
base_uti <- subset(base_inter, base_inter$UTI == 1)

#Dividindo OBITO
base_obito <- subset(base_inter, base_inter$OBITO == 1)


#Dividindo idades
idade_0_11_inter <- subset(base_inter, base_inter$IDADE < 12)
idade_12_18_inter <- subset(base_inter, base_inter$IDADE >= 12)
idade_0_11_uti <- subset(base_uti, base_uti$IDADE < 12)
idade_12_18_uti <- subset(base_uti, base_uti$IDADE >= 12)
idade_0_11_obito <- subset(base_obito, base_obito$IDADE < 12)
idade_12_18_obito <- subset(base_obito, base_obito$IDADE >= 12)



###########################################################################
#Função para estimação
###########################################################################
#Estimando relações - http://rstudio-pubs-static.s3.amazonaws.com/5752_fc41dca85dd24539bc99868697de83d0.html
esimativa_rr <- function(variavel, base){
  glm.regre <- glm(variavel ~ `Decil de IDH-M`, family="poisson"(link = "log"), data = base)
  ## Poisson model with SE estimated via robust variance estimator
  se_robusto <- coeftest(glm.regre, vcov = sandwich)
  ## Risk ratio (intercept and IC 95%) 
  table <- cbind(exp(coef(se_robusto)), exp(confint(se_robusto))) %>% as.data.frame()
  table$`Est (IC 95%)` <- paste0(round(table$V1,2), " (", round(table$`2.5 %`,2),"-",round(table$`97.5 %`,2),")")
  resultado <- list(glm.regre,table)
  return(resultado)
  
}

###########################################################################
#Internados
###########################################################################

idade_0_11_inter_amostra <- esimativa_rr(idade_0_11_inter$AMOSTRA, idade_0_11_inter)
idade_0_11_inter_raio_x <- esimativa_rr(idade_0_11_inter$DT_RAIOX, idade_0_11_inter)
idade_0_11_inter_tomo <- esimativa_rr(idade_0_11_inter$DT_TOMO, idade_0_11_inter)
idade_0_11_inter_vent <- esimativa_rr(idade_0_11_inter$SUPORT_VEN, idade_0_11_inter)
idade_0_11_inter_uti <- esimativa_rr(idade_0_11_inter$UTI, idade_0_11_inter)
idade_0_11_inter_obito <- esimativa_rr(idade_0_11_inter$OBITO, idade_0_11_inter)


idade_12_18_inter_amostra <- esimativa_rr(idade_12_18_inter$AMOSTRA, idade_12_18_inter)
idade_12_18_inter_raio_x <- esimativa_rr(idade_12_18_inter$DT_RAIOX, idade_12_18_inter)
idade_12_18_inter_tomo <- esimativa_rr(idade_12_18_inter$DT_TOMO, idade_12_18_inter)
idade_12_18_inter_vent <- esimativa_rr(idade_12_18_inter$SUPORT_VEN, idade_12_18_inter)
idade_12_18_inter_uti <- esimativa_rr(idade_12_18_inter$UTI, idade_12_18_inter)
idade_12_18_inter_obito <- esimativa_rr(idade_12_18_inter$OBITO, idade_12_18_inter)

inter_0_11 <- data.frame("Amostra (IC 95%)" = idade_0_11_inter_amostra[[2]][4],
          "RX (IC 95%)" = idade_0_11_inter_raio_x[[2]][4],
          "Tomo (IC 95%)" = idade_0_11_inter_tomo[[2]][4],
          "Ventilação (IC 95%)" = idade_0_11_inter_vent[[2]][4],
          "UTI (IC 95%)" = idade_0_11_inter_uti[[2]][4],
          "Óbito (IC 95%)" = idade_0_11_inter_obito[[2]][4])
names(inter_0_11) <- c("Amostra (IC 95%)", 
                     "RX (IC 95%)",
                     "Tomo (IC 95%)",
                     "Ventilação (IC 95%)",
                     "UTI (IC 95%)",
                     "Óbito (IC 95%)")


inter_12_18 <- data.frame("Amostra (IC 95%)" = idade_12_18_inter_amostra[[2]][4],
          "RX (IC 95%)" = idade_12_18_inter_raio_x[[2]][4],
          "Tomo (IC 95%)" = idade_12_18_inter_tomo[[2]][4],
          "Ventilação (IC 95%)" = idade_12_18_inter_vent[[2]][4],
          "UTI (IC 95%)" = idade_12_18_inter_uti[[2]][4],
          "Óbito (IC 95%)" = idade_12_18_inter_obito[[2]][4])

names(inter_12_18) <- c("Amostra (IC 95%)", 
                     "RX (IC 95%)",
                     "Tomo (IC 95%)",
                     "Ventilação (IC 95%)",
                     "UTI (IC 95%)",
                     "Óbito (IC 95%)")





###########################################################################
#UTI
###########################################################################

idade_0_11_uti_amostra <- esimativa_rr(idade_0_11_uti$AMOSTRA, idade_0_11_uti)
idade_0_11_uti_raio_x <- esimativa_rr(idade_0_11_uti$DT_RAIOX, idade_0_11_uti)
idade_0_11_uti_tomo <- esimativa_rr(idade_0_11_uti$DT_TOMO, idade_0_11_uti)
idade_0_11_uti_vent <- esimativa_rr(idade_0_11_uti$SUPORT_VEN, idade_0_11_uti)
idade_0_11_uti_obito <- esimativa_rr(idade_0_11_uti$OBITO, idade_0_11_uti)


idade_12_18_uti_amostra <- esimativa_rr(idade_12_18_uti$AMOSTRA, idade_12_18_uti)
idade_12_18_uti_raio_x <- esimativa_rr(idade_12_18_uti$DT_RAIOX, idade_12_18_uti)
idade_12_18_uti_tomo <- esimativa_rr(idade_12_18_uti$DT_TOMO, idade_12_18_uti)
idade_12_18_uti_vent <- esimativa_rr(idade_12_18_uti$SUPORT_VEN, idade_12_18_uti)
idade_12_18_uti_obito <- esimativa_rr(idade_12_18_uti$OBITO, idade_12_18_uti)

uti_0_11 <- data.frame("Amostra (IC 95%)" = idade_0_11_uti_amostra[[2]][4],
          "RX (IC 95%)" = idade_0_11_uti_raio_x[[2]][4],
          "Tomo (IC 95%)" = idade_0_11_uti_tomo[[2]][4],
          "Ventilação (IC 95%)" = idade_0_11_uti_vent[[2]][4],
          "Óbito (IC 95%)" = idade_0_11_uti_obito[[2]][4])
names(uti_0_11) <- c("Amostra (IC 95%)", 
                     "RX (IC 95%)",
                     "Tomo (IC 95%)",
                     "Ventilação (IC 95%)",
                     "Óbito (IC 95%)")

uti_12_18 <- data.frame("Amostra (IC 95%)" = idade_12_18_uti_amostra[[2]][4],
          "RX (IC 95%)" = idade_12_18_uti_raio_x[[2]][4],
          "Tomo (IC 95%)" = idade_12_18_uti_tomo[[2]][4],
          "Ventilação (IC 95%)" = idade_12_18_uti_vent[[2]][4],
           "Óbito (IC 95%)" = idade_12_18_uti_obito[[2]][4])

names(uti_12_18) <- c("Amostra (IC 95%)", 
                     "RX (IC 95%)",
                     "Tomo (IC 95%)",
                     "Ventilação (IC 95%)",
                     "Óbito (IC 95%)")

###########################################################################
#Obito
###########################################################################

idade_0_11_obito_amostra <- esimativa_rr(idade_0_11_obito$AMOSTRA, idade_0_11_obito)
idade_0_11_obito_raio_x <- esimativa_rr(idade_0_11_obito$DT_RAIOX, idade_0_11_obito)
idade_0_11_obito_tomo <- esimativa_rr(idade_0_11_obito$DT_TOMO, idade_0_11_obito)
idade_0_11_obito_vent <- esimativa_rr(idade_0_11_obito$SUPORT_VEN, idade_0_11_obito)
idade_0_11_obito_uti <- esimativa_rr(idade_0_11_obito$UTI, idade_0_11_obito)


idade_12_18_obito_amostra <- esimativa_rr(idade_12_18_obito$AMOSTRA, idade_12_18_obito)
idade_12_18_obito_raio_x <- esimativa_rr(idade_12_18_obito$DT_RAIOX, idade_12_18_obito)
idade_12_18_obito_tomo <- esimativa_rr(idade_12_18_obito$DT_TOMO, idade_12_18_obito)
idade_12_18_obito_vent <- esimativa_rr(idade_12_18_obito$SUPORT_VEN, idade_12_18_obito)
idade_12_18_obito_uti <- esimativa_rr(idade_12_18_obito$UTI, idade_12_18_obito)

obito_0_11 <- data.frame("Amostra (IC 95%)" = idade_0_11_obito_amostra[[2]][4],
          "RX (IC 95%)" = idade_0_11_obito_raio_x[[2]][4],
          "Tomo (IC 95%)" = idade_0_11_obito_tomo[[2]][4],
          "Ventilação (IC 95%)" = idade_0_11_obito_vent[[2]][4],
          "UTI (IC 95%)" = idade_0_11_obito_uti[[2]][4])
names(obito_0_11) <- c("Amostra (IC 95%)", 
                     "RX (IC 95%)",
                     "Tomo (IC 95%)",
                     "Ventilação (IC 95%)",
                     "UTI (IC 95%)")

          
obito_12_18 <- data.frame("Amostra (IC 95%)" = idade_12_18_obito_amostra[[2]][4],
          "RX (IC 95%)" = idade_12_18_obito_raio_x[[2]][4],
          "Tomo (IC 95%)" = idade_12_18_obito_tomo[[2]][4],
          "Ventilação (IC 95%)" = idade_12_18_obito_vent[[2]][4],
          "UTI (IC 95%)" = idade_12_18_obito_uti[[2]][4])
names(obito_12_18) <- c("Amostra (IC 95%)", 
                     "RX (IC 95%)",
                     "Tomo (IC 95%)",
                     "Ventilação (IC 95%)",
                     "UTI (IC 95%)")





```

*Tabela 1:* Internações em crianças de 0 a 11 ano
```{r echo=FALSE}
knitr::kable(inter_0_11)
```

*Tabela 2:* Internações em crianças de 12 a 18 ano
```{r echo=FALSE}
knitr::kable(inter_12_18)
```

*Tabela 3:* Internações em UTI em crianças de 0 a 11 ano
```{r echo=FALSE}
knitr::kable(uti_0_11)
```

*Tabela 4:* Internações em UTI em crianças de 12 a 18 ano
```{r echo=FALSE}
knitr::kable(uti_12_18)
```

*Tabela 5:* Óbitos em crianças de 0 a 11 ano
```{r echo=FALSE}
knitr::kable(obito_0_11)
```

*Tabela 6:* Óbitos crianças de 12 a 18 ano
```{r echo=FALSE}
knitr::kable(obito_12_18)
```